server:
  port: 8090
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hyllovedf/spring-cloud-config.git
          username: hyllovedf
          password: hyllovedf0808
