server:
  port: 8010
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cloud?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  application:
    name: eureka-consumer-movie
  http:
    multipart:
      max-file-size: 2000Mb
      max-request-size: 2500mb
logging:
  level:
    root: info
    #feign的logger.level只对debug级别日志作出响应
    com.df.client.UserClient: debug
info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@
eureka:
  instance:
    #将自己ip注册到eureka server上
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
